// react-app/src/components/Product.js
import React from 'react';
import { Link } from 'react-router-dom';
import Rating from './Rating';
import { Card } from 'react-bootstrap';

const Product = ({ product }) => {
	return (
		<Card className='my-3 p-3 rounded'>
			<Link to={`/product/${product._id}`}>
				<Card.Img src={product.image} variant='top' />
			</Link>

			<Card.Body>
				<Link to={`/product/${product._id}`}>
					<Card.Title as='div'>
						<strong>{product.name}</strong>
					</Card.Title>
				</Link>

				<Card.Text as='div'>
					<Rating
						value={product.rating}
						text={`${product.numReviews} reviews`}
					/>
				</Card.Text>
				<Card.Text as='h3'>${product.price}</Card.Text>
			</Card.Body>
		</Card>
	);
};

export default Product;

// vue-app/src/components/Product.vue
<template>
  <div class="my-3 p-3 rounded card">
    <router-link :to="`/product/${product._id}`">
      <img :src="product.image" class="card-img-top" />
    </router-link>
    <div class="card-body">
      <router-link :to="`/product/${product._id}`">
        <div class="card-title">
          <strong>{{ product.name }}</strong>
        </div>
      </router-link>
      <div class="card-text">
        <rating
          :value="product.rating"
          :text="`${product.numReviews} reviews`"
        ></rating>
      </div>
      <h3 class="card-text">${{ product.price }}</h3>
    </div>
  </div>
</template>

<script>
import Rating from "./Rating";
export default {
  components: { Rating },
  props: ["product"]
};
</script>

<style></style>
