// react-app/src/screens/HomeScreen.js
import React, { useEffect, useState } from 'react';
import { Row, Col } from 'react-bootstrap';
import Product from '../components/Product';
import axios from 'axios';

const HomeScreen = () => {
	const [products, setProducts] = useState([]);
	useEffect(() => {
		const getProducts = async () => {
			try {
				const response = await axios.get(
					'http://localhost:5500/api/v1/products',
				);
				setProducts(response.data);
			} catch (error) {
				console.log(error.message);
			}
		};
		getProducts();
	}, []);

	return (
		<>
			<h1>Latest Products</h1>
			<Row>
				{products.map((product) => (
					<Col key={product._id} sm={12} md={6} lg={4} xl={3}>
						<Product product={product} />
					</Col>
				))}
			</Row>
		</>
	);
};

export default HomeScreen;

// vue-app/src/screens/HomeScreen.vue
<template>
  <h1>Latest Products</h1>
  <div class="row">
    <div
      v-for="product in products"
      :key="product._id"
      class="col-xl-3 col-lg-4 col-md-6 col-sm-12"
    >
      <product :product="product"></product>
    </div>
  </div>
</template>

<script>
import { ref } from "vue";
import Product from "../components/Product";
import axios from "axios";
export default {
  components: { Product },
  setup() {
    const products = ref([]);
    const getProducts = async () => {
      try {
        const response = await axios.get("http://localhost:5500/api/products");
        products.value = response.data;
      } catch (error) {
        console.log(error);
      }
    };
    getProducts();
    return { products };
  }
};
</script>

<style></style>
