// vue-app/src/screens/CartScreen.vue
<template>
  <div class="row">
    <div class="col-md-8">
      <h1>Shopping Cart</h1>
      <div
        v-if="cartItems.length === 0"
        role="alert"
        class="face alert alert-info show"
      >
        Your Cart is empty <router-link to="/cart">Go back</router-link>
      </div>
      <div v-if="cartItems.length > 0" class="list-group list-group-flush">
        <div
          v-for="item in cartItems"
          :key="item.product"
          class="list-group-item"
        >
          <div class="row">
            <div class="col-md-2">
              <img
                :src="item.image"
                :alt="item.name"
                class="img-fluid rounded"
              />
            </div>
            <div class="col-md-3">
              <router-link :to="'/product/' + item.product">{{
                item.name
              }}</router-link>
            </div>
            <div class="col-md-2">${{ item.price }}</div>
            <div class="col-md-2">
              <select
                class="form-control"
                :value="item.qty"
                @change="changeQtyHandler(item.product, $event)"
              >
                <option
                  v-for="num in item.countInStock"
                  :key="num"
                  :value="num"
                  >{{ num }}</option
                >
              </select>
            </div>
            <div class="col-md-2">
              <button
                type="button"
                class="btn btn-light"
                @click="removeFromCartHandler(item.product)"
              >
                <i className="fas fa-trash"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="list-group list-group-flush">
          <div class="list-group-item">
            <h2>
              Subtotal ({{
                cartItems.reduce((acc, item) => acc + +item.qty, 0)
              }}) items
            </h2>
            ${{
              cartItems
                .reduce((acc, item) => acc + +item.qty * +item.price, 0)
                .toFixed(2)
            }}
          </div>
          <div class="list-group-item">
            <button
              type="button"
              class="btn-block btn btn-primary"
              :disabled="cartItems.length === 0"
              @click="checkoutHandler"
            >
              Proceed to Checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from "vue";
import { useStore } from "vuex";
import { useRoute, useRouter } from "vue-router";
export default {
  setup() {
    const { dispatch, state } = useStore();
    const { params, query } = useRoute();
    const { replace } = useRouter();

    const productId = computed(() => params.productId);
    const qty = computed(() => query.qty);

    const cartItems = computed(() => state.cartStore.cartItems);

    const addToCartHandler = () => {
      productId.value &&
        qty.value &&
        dispatch("addToCart", { productId: productId.value, qty: +qty.value });
      replace("/cart");
    };
    addToCartHandler();

    const changeQtyHandler = (productId, event) => {
      dispatch("addToCart", { productId, qty: +event.target.value });
    };

    const removeFromCartHandler = productId => {
      dispatch("removeFromCart", productId);
    };

    const checkoutHandler = () => {
      console.log("Checkout");
    };

    return {
      qty,
      productId,
      cartItems,
      changeQtyHandler,
      removeFromCartHandler,
      checkoutHandler
    };
  }
};
</script>

<style></style>

// react-app/src/screens/CartScreen.js
import React, { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import {
	Row,
	Col,
	ListGroup,
	Image,
	Form,
	Button,
	Card,
} from 'react-bootstrap';
import Message from '../components/shared/Message';
import { addToCart, removeFromCart } from '../actions/cartActions';

const CartScreen = ({ match, location, history }) => {
	const productId = match.params.productId;
	const qty = location.search ? +location.search.split('=')[1] : 1;

	const dispatch = useDispatch();

	const cart = useSelector((state) => state.cart);
	const { cartItems } = cart;

	useEffect(() => {
		if (productId) {
			const addToCartHandler = () => {
				dispatch(addToCart(productId, qty));
				history.push('/cart');
			};
			addToCartHandler();
		}
	}, [dispatch, history, productId, qty]);

	const removeFromCartHandler = (productId) => {
		dispatch(removeFromCart(productId));
	};

	const checkoutHandler = () => {
		console.log('checkout');
		history.push('/login?redirect=shipping');
	};

	return (
		<Row>
			<Col md={8}>
				<h1>Shopping Cart</h1>
				{cartItems.length === 0 ? (
					<Message>
						Your Cart is empty <Link to='/'>Go Back</Link>
					</Message>
				) : (
					<ListGroup variant='flush'>
						{cartItems.map((item) => (
							<ListGroup.Item key={item.product}>
								<Row>
									<Col md={2}>
										<Image src={item.image} alt={item.name} fluid rounded />
									</Col>
									<Col md={3}>
										<Link to={'/product/' + item.product}>{item.name}</Link>
									</Col>
									<Col md={2}>${item.price}</Col>
									<Col md={2}>
										<Form.Control
											as='select'
											value={item.qty}
											onChange={(e) =>
												dispatch(addToCart(item.product, +e.target.value))
											}
										>
											{[...Array(item.countInStock).keys()].map((x) => (
												<option key={x + 1} value={x + 1}>
													{x + 1}
												</option>
											))}
										</Form.Control>
									</Col>
									<Col md={2}>
										<Button
											type='button'
											variant='light'
											onClick={() => removeFromCartHandler(item.product)}
										>
											<i className='fas fa-trash'></i>
										</Button>
									</Col>
								</Row>
							</ListGroup.Item>
						))}
					</ListGroup>
				)}
			</Col>
			<Col md={4}>
				<Card>
					<ListGroup variant='flush'>
						<ListGroup.Item>
							<h2>
								Subtotal ({cartItems.reduce((acc, item) => acc + item.qty, 0)})
								items
							</h2>
							$
							{cartItems
								.reduce((acc, item) => acc + item.qty * item.price, 0)
								.toFixed(2)}
						</ListGroup.Item>
						<ListGroup.Item>
							<Button
								type='button'
								className='btn-block'
								disabled={cartItems.length === 0}
								onClick={checkoutHandler}
							>
								Proceed To Checkout
							</Button>
						</ListGroup.Item>
					</ListGroup>
				</Card>
			</Col>
		</Row>
	);
};

export default CartScreen;
