// vue-app/src/screens/ProductScreen.vue
<template>
  <router-link to="/" class="btn btn-light my-3">Go Back</router-link>
  <div class="row">
    <div class="col-md-6">
      <img :src="product.image" :alt="product.name" class="img-fluid" />
    </div>
    <div class="col-md-3">
      <div class="list-group list-group-flush">
        <div class="list-group-item">
          <h3>{{ product.name }}</h3>
        </div>
        <div class="list-group-item">
          <div class="rating">
            <rating
              :value="+product.rating"
              :text="`${product.numReviews} reviews`"
            ></rating>
          </div>
        </div>
        <div class="list-group-item">Price: ${{ product.price }}</div>
        <div class="list-group-item">
          Description: {{ product.description }}
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="list-group list-group-flush">
          <div class="list-group-item">
            <div class="row">
              <div class="col">Price</div>
              <div class="col">
                <strong>${{ product.price }}</strong>
              </div>
            </div>
          </div>
          <div class="list-group-item">
            <div class="row">
              <div class="col">Status</div>
              <div class="col">
                {{ product.countInStock > 0 ? "In Stock" : "Out of Stock" }}
              </div>
            </div>
          </div>
          <div class="list-group-item">
            <button
              type="button"
              class="btn-block btn btn-primary"
              :disabled="product.countInStock === 0"
            >
              Add To Cart
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { useRoute } from "vue-router";
import axios from "axios";
import Rating from "../components/Rating";
import { ref } from "vue";
export default {
  components: { Rating },
  setup() {
    const route = useRoute();
    const { productId } = route.params;

    const product = ref([]);
    const getProducts = async () => {
      try {
        const response = await axios.get(
          "http://localhost:5500/api/products/" + productId
        );
        product.value = response.data;
      } catch (error) {
        console.log(error);
      }
    };

    getProducts();

    return { product };
  }
};
</script>

<style></style>

// react-app/src/screens/ProductScreen.js
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Row, Col, Image, ListGroup, Card, Button } from 'react-bootstrap';
import Rating from '../components/Rating';
import axios from 'axios';

const ProductScreen = ({ match }) => {
	const [product, setProduct] = useState([]);

	useEffect(() => {
		const getProduct = async () => {
			try {
				const response = await axios.get(
					'http://localhost:5500/api/v1/products/' + match.params.productId,
				);
				setProduct(response.data);
			} catch (error) {
				console.log(error);
			}
		};

		getProduct();
	}, [match]);

	return (
		<>
			<Link to='/' className='btn btn-light my-3'>
				Go Back
			</Link>
			<Row>
				<Col md={6}>
					<Image src={product.image} alt={product.name} fluid />
				</Col>
				<Col md={3}>
					<ListGroup variant='flush'>
						<ListGroup.Item>
							<h3>{product.name}</h3>
						</ListGroup.Item>
						<ListGroup.Item>
							<Rating
								value={+product.rating}
								text={`${product.numReviews} reviews`}
							/>
						</ListGroup.Item>
						<ListGroup.Item>Price: ${product.price}</ListGroup.Item>
						<ListGroup.Item>Description: {product.description}</ListGroup.Item>
					</ListGroup>
				</Col>
				<Col md={3}>
					<Card>
						<ListGroup variant='flush'>
							<ListGroup.Item>
								<Row>
									<Col>Price:</Col>
									<Col>
										<strong>${product.price}</strong>
									</Col>
								</Row>
							</ListGroup.Item>
							<ListGroup.Item>
								<Row>
									<Col>Status:</Col>
									<Col>
										{product.countInStock > 0 ? 'In Stock' : 'Out of Stock'}
									</Col>
								</Row>
							</ListGroup.Item>

							<ListGroup.Item>
								<Button
									className='btn-block'
									type='button'
									disabled={product.countInStock === 0}
								>
									Add To Cart
								</Button>
							</ListGroup.Item>
						</ListGroup>
					</Card>
				</Col>
			</Row>
		</>
	);
};

export default ProductScreen;
